export const MOCK_INVENTORY_ITEMS = [
  {
    inventory_id: 6,
    kot_id: 4,
    tuck_shop_item_id: 14,
    currentQuantity: 25,
    reservedQuantity: 10,
    reorderLevel: 7,
    unit: 'can',
    isAvailable: true,
    lastRestockedAt: '2026-08-16T10:10:03.000Z',
    item: { item_id: 14, itemName: 'Cold Coffee', category_id: 2, type: 'veg', description: 'Chilled creamy cold coffee', image: [], price: 60, isActive: true, category: { category_id: 2, name: 'Beverages' } },
    availableQuantity: 15,
    isLowStock: false,
  },
  {
    inventory_id: 7,
    kot_id: 4,
    tuck_shop_item_id: 26,
    currentQuantity: 8,
    reservedQuantity: 2,
    reorderLevel: 10,
    unit: 'piece',
    isAvailable: true,
    lastRestockedAt: '2026-08-18T08:30:00.000Z',
    item: { item_id: 26, itemName: 'Chicken Burger', category_id: 1, type: 'non-veg', description: 'Mini chicken burger', image: [], price: 40, isActive: true, category: { category_id: 1, name: 'Snacks' } },
    availableQuantity: 6,
    isLowStock: true,
  },
  {
    inventory_id: 8,
    kot_id: 4,
    tuck_shop_item_id: 18,
    currentQuantity: 12,
    reservedQuantity: 0,
    reorderLevel: 5,
    unit: 'piece',
    isAvailable: false,
    lastRestockedAt: '2026-08-17T09:15:00.000Z',
    item: { item_id: 18, itemName: 'Paneer Roll', category_id: 1, type: 'veg', description: 'Spiced paneer roll', image: [], price: 75, isActive: true, category: { category_id: 1, name: 'Snacks' } },
    availableQuantity: 12,
    isLowStock: false,
  },
  {
    inventory_id: 9,
    kot_id: 4,
    tuck_shop_item_id: 20,
    currentQuantity: 0,
    reservedQuantity: 0,
    reorderLevel: 6,
    unit: 'piece',
    isAvailable: false,
    lastRestockedAt: '2026-08-15T11:00:00.000Z',
    item: { item_id: 20, itemName: 'Muffin', category_id: 3, type: 'veg', description: 'Chocolate muffin', image: [], price: 45, isActive: true, category: { category_id: 3, name: 'Desserts' } },
    availableQuantity: 0,
    isLowStock: false,
  },
];
